#!/bin/bash
cd /var/www/html
sudo composer install 
# sudo composer update
php artisan key:generate
php artisan migrate

# sudo systemctl apache2 restart

# cd /var/www/html
# npm cache clean --force
# sudo npm install

sudo /etc/init.d/apache2 restart

sudo npm run build